name: prova_pratica_01
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=3.5.0 <3.6.0"

dependencies:
  mailer: ^6.4.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.0
