include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Boas práticas recomendadas
    always_use_package_imports: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true

    # Estilo
    sort_constructors_first: true
    lines_longer_than_80_chars: false # coloque true se quiser código mais compacto
    prefer_single_quotes: true

    # Null Safety e segurança
    avoid_returning_null_for_future: true
    unnecessary_nullable_return_type: true

    # Código limpo
    avoid_unused_constructor_parameters: true
    avoid_init_to_null: true
    prefer_final_fields: true
    prefer_final_locals: true
