name: atividade4
description: Aplicação de linha de comando em Dart com SQLite3.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  sqlite3: ^2.7.6
  path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
